name: Frontend Continuous Integration

on:
  pull_request:
    branches: [main]
    paths: ['starter/frontend/**']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.14'
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.14'
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json
      - run: npm ci
      - run: CI=true npm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.14'
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json
      - run: npm ci
      - run: docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .